[project]
name = "ff-custom-arena"
version = "0.1.0"
dependencies = [
    "flask",
    "flask-login",
    "flask-sqlalchemy",
    "flask-migrate",
    "flask-wtf",
    "flask-limiter",
    "flask-socketio",
    "flask-cors",
    "python-dotenv",
    "requests"
]

[tool.vercel]
entrypoint = "run:app"
