[project]
name = "ff-custom-arena"
version = "0.1.0"
dependencies = [
    "flask",
    "flask-login",
    "flask-sqlalchemy",
    "flask-migrate",
    "flask-wtf",
    "flask-limiter",
    "flask-socketio",
    "python-socketio",
    "python-engineio",
    "flask-cors",
    "pymysql",
    "cryptography",
    "python-dotenv",
    "requests",
    "pillow",
    "reportlab"
]

[tool.vercel]
entrypoint = "run:app"
